"""
pdf_utils.py — Generate a formatted PDF meeting report using ReportLab.
"""

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
import datetime


def generate_pdf(summary: str, actions: str, decisions: str,
                 filename: str = "meeting_report.pdf") -> str:
    """Build a clean PDF report and return the filename."""

    doc    = SimpleDocTemplate(
        filename,
        pagesize=A4,
        leftMargin=0.85 * inch,
        rightMargin=0.85 * inch,
        topMargin=0.9 * inch,
        bottomMargin=0.9 * inch,
    )
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontSize=20,
        textColor=colors.HexColor("#0F172A"),
        spaceAfter=4,
    )
    meta_style = ParagraphStyle(
        "Meta",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.HexColor("#64748B"),
        spaceAfter=16,
    )
    section_style = ParagraphStyle(
        "SectionHead",
        parent=styles["Heading2"],
        fontSize=13,
        textColor=colors.HexColor("#1E3A8A"),
        spaceBefore=18,
        spaceAfter=8,
        borderPad=0,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["BodyText"],
        fontSize=10,
        leading=16,
        textColor=colors.HexColor("#334155"),
        spaceAfter=6,
    )

    def _lines_to_paragraphs(text: str, style):
        """Convert newline-separated text into a list of Paragraphs."""
        elems = []
        for line in text.strip().splitlines():
            line = line.strip()
            if line:
                elems.append(Paragraph(line, style))
        return elems if elems else [Paragraph("None identified.", style)]

    now = datetime.datetime.now().strftime("%d %B %Y, %H:%M")
    content = [
        Paragraph("AI Meeting Assistant", title_style),
        Paragraph(f"Meeting Analysis Report &nbsp;·&nbsp; Generated {now}", meta_style),
        HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E2E8F0"), spaceAfter=12),

        Paragraph("📋 Meeting Summary", section_style),
        *_lines_to_paragraphs(summary, body_style),
        Spacer(1, 8),

        HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E2E8F0"), spaceAfter=8),
        Paragraph("✅ Action Items", section_style),
        *_lines_to_paragraphs(actions, body_style),
        Spacer(1, 8),

        HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E2E8F0"), spaceAfter=8),
        Paragraph("🔑 Key Decisions", section_style),
        *_lines_to_paragraphs(decisions, body_style),
        Spacer(1, 16),

        HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E2E8F0"), spaceAfter=8),
        Paragraph("Generated by AI Meeting Assistant · Confidential", meta_style),
    ]

    doc.build(content)
    return filename
